/**
 * Auto-generated by: https://github.com/pmndrs/gltfjsx
 * Author: omarelone (https://sketchfab.com/omarelone)
 * License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
 * Source: https://sketchfab.com/3d-models/pumping-heart-model-6f815b9822dc479eae0a17b8dcab9c75
 * Title: PUMPING HEART MODEL
 *
 * @format
 */

import React, { useEffect, useRef } from "react";
import { useGLTF, useAnimations, useMask, Mask } from "@react-three/drei";

export const Model = (props) => {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("models/valen.gltf");
  const { actions } = useAnimations(animations, group);

  useEffect(() => {
    console.info(actions);
    actions["Take 001"].play();
  }, [actions]);

  return (
    <>
      <group ref={group} {...props} dispose={null}>
        <group name="Sketchfab_Scene">
          <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
            <group
              name="f6bcb81c5d674405b84df409a29b9a55fbx"
              rotation={[Math.PI / 2, 0, 0]}
            >
              <group name="Object_2">
                <group name="RootNode">
                  <group
                    name="BASE_HEART"
                    position={[-0.676, 38.876, -0.255]}
                    rotation={[-Math.PI / 2, 0, 0]}
                  >
                    <group name="Object_5" position={[-0.09, 0, -38.876]}>
                      <mesh
                        name="BASE_HEART_Material_#41_0"
                        castShadow
                        receiveShadow
                        geometry={nodes["BASE_HEART_Material_#41_0"].geometry}
                        material={materials.Material_41}
                      />
                    </group>
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </>
  );
};

useGLTF.preload("models/valen.gltf");
