/**
 * Auto-generated by: https://github.com/pmndrs/gltfjsx
 * Author: sergeilihandristov (https://sketchfab.com/sergeilihandristov)
 * License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
 * Source: https://sketchfab.com/3d-models/teddy-bear-fe59581a0be24cb1802c443a2a9bc5ae
 * Title: Teddy Bear
 *
 * @format
 */

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

const Bear = (props) => {
  const { nodes, materials } = useGLTF("models/bear.gltf");
  return (
    <group {...props} dispose={null}>
      <group scale={0.1}>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.bear_hp_tex_u1_v1_0.geometry}
            material={materials.tex_u1_v1}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.bear_hp_tex_u1_v1_0_1.geometry}
            material={materials.tex_u1_v1}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.bear_hp_tex_u1_v1_0_2.geometry}
            material={materials.tex_u1_v1}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.bear_hp_tex_u1_v1_0_3.geometry}
            material={materials.tex_u1_v1}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.bear_hp_tex_u1_v1_0_4.geometry}
            material={materials.tex_u1_v1}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.bear_hp_tex_u1_v1_0_5.geometry}
            material={materials.tex_u1_v1}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.bear_hp_tex_u1_v1_0_6.geometry}
            material={materials.tex_u1_v1}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.bear_hp_tex_u1_v1_0_7.geometry}
            material={materials.tex_u1_v1}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.bear_hp_tex_u1_v1_0_8.geometry}
            material={materials.tex_u1_v1}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.bear_hp_tex_u1_v1_0_9.geometry}
            material={materials.tex_u1_v1}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.bear_hp_tex_u1_v1_0_10.geometry}
            material={materials.tex_u1_v1}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.bear_hp_tex_u1_v1_0_11.geometry}
            material={materials.tex_u1_v1}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.floor__0.geometry}
          material={materials.floor__0}
          position={[0, -56.158, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
      </group>
    </group>
  );
};

useGLTF.preload("models/bear.gltf");

export default Bear;
